name: plugin-check

on:
  push:
    branches:
      - main
      - "releases/*"
  pull_request:

jobs:
  plugin-check:
    name: WordPress Plugin Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare plugin build
        run: |
          rsync -av ./ ./plugin-check \
            --delete \
            --exclude '.git/' \
            --exclude '.github/' \
            --exclude 'node_modules/' \
            --exclude '.vscode/' \
            --exclude '.idea/' \
            --exclude '.DS_Store' \
            --exclude '*.log' \
            --exclude '.env*' \
            --exclude 'docs/' \
            --exclude 'scripts/' \
            --exclude '.gitignore'

      - name: Run Plugin Check
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: "./plugin-check"
          ignore-codes: |
            plugin_updater_detected
            update_modification_detected
            WordPress.WP.I18n.TextDomainMismatch
            WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
            WordPress.Security.ValidatedSanitizedInput.MissingUnslash
            WordPress.Security.ValidatedSanitizedInput.InputNotValidated
